// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: msg.proto

#include "msg.pb.h"
#include "msg.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* verify_service_method_names[] = {
  "/message.verify_service/get_verify_code",
};

std::unique_ptr< verify_service::Stub> verify_service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< verify_service::Stub> stub(new verify_service::Stub(channel));
  return stub;
}

verify_service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_get_verify_code_(verify_service_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status verify_service::Stub::get_verify_code(::grpc::ClientContext* context, const ::message::get_verify_req& request, ::message::get_verify_rsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::get_verify_req, ::message::get_verify_rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_verify_code_, context, request, response);
}

void verify_service::Stub::experimental_async::get_verify_code(::grpc::ClientContext* context, const ::message::get_verify_req* request, ::message::get_verify_rsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::get_verify_req, ::message::get_verify_rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_verify_code_, context, request, response, std::move(f));
}

void verify_service::Stub::experimental_async::get_verify_code(::grpc::ClientContext* context, const ::message::get_verify_req* request, ::message::get_verify_rsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_verify_code_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::get_verify_rsp>* verify_service::Stub::PrepareAsyncget_verify_codeRaw(::grpc::ClientContext* context, const ::message::get_verify_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::get_verify_rsp, ::message::get_verify_req, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_verify_code_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::get_verify_rsp>* verify_service::Stub::Asyncget_verify_codeRaw(::grpc::ClientContext* context, const ::message::get_verify_req& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_verify_codeRaw(context, request, cq);
  result->StartCall();
  return result;
}

verify_service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      verify_service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< verify_service::Service, ::message::get_verify_req, ::message::get_verify_rsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](verify_service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::get_verify_req* req,
             ::message::get_verify_rsp* resp) {
               return service->get_verify_code(ctx, req, resp);
             }, this)));
}

verify_service::Service::~Service() {
}

::grpc::Status verify_service::Service::get_verify_code(::grpc::ServerContext* context, const ::message::get_verify_req* request, ::message::get_verify_rsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

